const katex_macros = {
  "\\equals": "\\texttt{=}",
  "\\nequals": "\\texttt{!=}",
  "\\plus": "\\texttt{+}",
  "\\minus": "\\texttt{-}",
  "\\lt": "\\texttt{<}",
  "\\gt": "\\texttt{>}",
  "\\lte": "\\texttt{<=}",
  "\\gte": "\\texttt{>=}",
  "\\lbracket": "\\texttt{[}",
  "\\rbracket": "\\texttt{]}",
  "\\lpar": "\\texttt{(}",
  "\\rpar": "\\texttt{)}",
  "\\relate": "\\texttt{R}",
  "\\nrelate": "\\cancel{\\texttt{R}}",
  "\\dom": "\\text{dom}\\left(#1\\right)",
  "\\codom": "\\text{codom}\\left(#1\\right)",
  "\\abs": "\\left| #1 \\right|",
  "\\setof": "\\left\\lbrace #1 \\right\\rbrace",
  // unicode courier
  "\\monoA":"𝙰",
  "\\monoa":"𝚊",
  "\\monoB":"𝙱",
  "\\monob":"𝚋",
  "\\monoC":"𝙲",
  "\\monoc":"𝚌",
  "\\monoD":"𝙳",
  "\\monod":"𝚍",
  "\\monoE":"𝙴",
  "\\monoe":"𝚎",
  "\\monoF":"𝙵",
  "\\monof":"𝚏",
  "\\monoG":"𝙶",
  "\\monog":"𝚐",
  "\\monoH":"𝙷",
  "\\monoh":"𝚑",
  "\\monoI":"𝙸",
  "\\monoi":"𝚒",
  "\\monoJ":"𝙹",
  "\\monoj":"𝚓",
  "\\monoK":"𝙺",
  "\\monok":"𝚔",
  "\\monoL":"𝙻",
  "\\monol":"𝚕",
  "\\monoM":"𝙼",
  "\\monom":"𝚖",
  "\\monoN":"𝙽",
  "\\monon":"𝚗",
  "\\monoO":"𝙾",
  "\\monoo":"𝚘",
  "\\monoP":"𝙿",
  "\\monop":"𝚙",
  "\\monoQ":"𝚀",
  "\\monoq":"𝚚",
  "\\monoR":"𝚁",
  "\\monor":"𝚛",
  "\\monoS":"𝚂",
  "\\monos":"𝚜",
  "\\monoT":"𝚃",
  "\\monot":"𝚝",
  "\\monoU":"𝚄",
  "\\monou":"𝚞",
  "\\monoV":"𝚅",
  "\\monov":"𝚟",
  "\\monoW":"𝚆",
  "\\monow":"𝚠",
  "\\monoX":"𝚇",
  "\\monox":"𝚡",
  "\\monoY":"𝚈",
  "\\monoy":"𝚢",
  "\\monoZ":"𝚉",
  "\\monoz":"𝚣",
};

export default katex_macros;
